apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-ms-deploy
spec:
  selector:
    matchLabels:
      app: email-app
  template:
    metadata:
      labels:
        app: email-app
    spec:
      containers:
      - name: email-container
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.2.3
        ports:
          - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"