apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWUxMjM=
  mongo-root-password: cXdlMzIx
  mongodb-secrets-file: |
    asd123
    asd213
