apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ms
spec:
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-container
        image: gcr.io/google-samples/microservices-demo/frontend:v0.2.3
        ports:
        - containerPort: 8080
        #livenessProbe:
        #  periodSeconds: 5
        #  exec:
        #    command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-liveness-probe"
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: 8080
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-readiness-probe"
        resources:  
          requests:
            memory: 150Mi
            cpu: 50m
          limits:
            cpu: 70m
            memory: 200Mi
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog-service:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:7000"
        - name: CART_SERVICE_ADDR
          value: "cart-service:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendation-service:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkout-service:5050"
        - name: AD_SERVICE_ADDR
          value: "ad-service:9555"
        - name: ENABLE_PROFILER
          value: "0"
