apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployName }}
spec:
  replicas: {{ .Values.appReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: "{{ .Values.containerImage }}:{{ .Values.imageTag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
        - mountPath: {{ .Values.mountPath }}
          name: {{ .Values.volumeName }}
      volumes:
      - name: {{ .Values.volumeName }}
        emptyDir: {}