deployName: productcatalog-deployment
appReplicas: 1
appName: productcatalog-app
containerName: productcatalog-container
containerImage: gcr.io/google-samples/microservices-demo/productcatalogservice
imageTag: v0.2.3
containerPort: 3550
containerEnvVars:
- name: PORT
  value: "3550"
- name: DISABLE_PROFILER
  value: "1"

serviceName: productcatalog-service
serviceType: ClusterIP
servicePort: 3550
targetPort: 3550