apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-ms
spec:
  selector:
    matchLabels:
      app: shipping-app
  template:
    metadata:
      labels:
        app: shipping-app
    spec:
      containers:
      - name: shipping-container
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.3
        ports:
        - containerPort: 50051
        env:
        - name: "PORT"
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
