apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-ms-deploy
spec:
  selector:
    matchLabels:
      app: checkout-app
  template:
    metadata:
      labels:
        app: checkout-app
    spec:
      containers:
      - name: checkout-container
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.3
        ports:
          - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog-service:3550"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "payment-service:50051"
        - name: EMAIL_SERVICE_ADDR
          value: "email-service:5000"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:7000"
        - name: CART_SERVICE_ADDR
          value: "cart-service:7070"