apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-ms
spec:
  selector:
    matchLabels:
      app: recommendation-app
  template:
    metadata:
      labels:
        app: recommendation-app
    spec:
      containers:
      - name: recommendation-container
        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalog-service:3550"
        - name: DISABLE_PROFILER
          value: "1"
          